# Generated by Django 3.1.4 on 2024-03-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_date', models.CharField(max_length=225)),
                ('return_date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=225)),
                ('password', models.CharField(max_length=225)),
                ('usertype', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='vendor',
            fields=[
                ('vendor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('license_num', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('pin', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('phone', models.CharField(max_length=225)),
                ('pin', models.CharField(max_length=225)),
                ('city', models.CharField(max_length=225)),
                ('email', models.CharField(max_length=225)),
                ('login', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_details', models.CharField(max_length=225)),
                ('rate', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('duration', models.CharField(max_length=225)),
                ('start_date', models.CharField(max_length=225)),
                ('end_date', models.CharField(max_length=225)),
                ('budget', models.CharField(max_length=225)),
                ('equipment_requirement', models.CharField(max_length=225)),
                ('posted_date', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.booking')),
            ],
        ),
        migrations.CreateModel(
            name='equipment',
            fields=[
                ('equipment_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=225)),
                ('description', models.CharField(max_length=225)),
                ('price_per_day', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.vendor')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('complaint_id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint', models.CharField(max_length=225)),
                ('reply', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('status', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.equipment'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.user'),
        ),
    ]
