# Generated by Django 3.1.4 on 2024-03-05 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcb_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='fcb_app.vendor'),
            preserve_default=False,
        ),
    ]
