# Generated by Django 3.1.4 on 2024-03-05 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcb_app', '0002_review_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('feedback_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=225)),
                ('date', models.CharField(max_length=225)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.user')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fcb_app.vendor')),
            ],
        ),
    ]
