# Generated by Django 3.1.4 on 2024-03-05 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fcb_app', '0003_auto_20240305_1339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
    ]
